@startuml "Email Sorter"


class DataRow {
    -y : double
    -x : double[]
    #DataRow(double y, double[] x)
    +double getDependentVars()
    +double[] getIndependentVars()
}

class DataSet {
    -data : ArrayList<DataRow>
    #DataSet(String filename)
    +ArrayList<DataRow> getRows()
}

class FeatureProcessor {
    -top_ten : String[]
    -emailCount : int
    -totalWordLength : int
    +int getAvgLength()
}

class Model {
    -ham : FeatureProcessor
    -spam : FeatureProcessor
    -trainingData : DataSet
}

@enduml